-- Matches the pre-Flyway data model. Existing databases require an audited,
-- explicit baseline at version 1; automatic baselining is disabled.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titolo VARCHAR(200) NOT NULL,
    descrizione VARCHAR(5000),
    data TIMESTAMP(6) NOT NULL,
    luogo VARCHAR(255) NOT NULL,
    categoria VARCHAR(80) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);
